# Operations Manager credentials to set
pcf_opsman_admin_username: user
pcf_opsman_admin_password: password
opsman_url: opsman.doma.in

# Elastic Runtime Domain
pcf_ert_domain: doma.in

# GitHub token with repo or public_repo scope
github_token: some_token

pcf_sys_domain: sys.doma.in

prometheus_bosh_client: prometheus-bosh
prometheus_bosh_secret: prometheus-client-secret
prometheus_firehose_client: prometheus-firehose
prometheus_firehose_secret: prometheus-client-secret
prometheus_cf_client: prometheus-cf
prometheus_cf_secret: prometheus-client-secret
prometheus_cf_deployment_name: cf

deploy_azs: "[az1, az2]"
deploy_network: infrastructure
deploy_vm_password: #(echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0)
deploy_nginx_ip: 1.1.1.1
deploy_vm_type_micro: micro
deploy_vm_type_small: small

bosh_creds_source: opsman

# Fill in if you use `bosh_creds_source: manual`
bosh_username: ""
bosh_password: ""
director_ip: ""
bosh_ca: ""
nats_machines: ""
nats_username: ""
nats_password: ""

grafana_admin_password: grafana!
